"""
Séma-létrehozó segéd az ÚJ Supabase projekthez (PlanSmart → MyMins migráció).

Miért nem futtatja közvetlenül a DDL-t? A Supabase REST API-n (PostgREST) NEM
megy DDL, és csak service_role kulcsunk van (a Management API personal access
tokent igényelne). Ezért ez a script ÖSSZEFŰZI a migration SQL fájlokat egyetlen
fájlba, amit a felhasználó a Supabase SQL Editorba másol és lefuttat.

KRITIKUS átalakítás — id-megőrzés:
    A migrationök `id bigint generated ALWAYS as identity` oszlopokat hoznak
    létre. GENERATED ALWAYS esetén a PostgREST NEM tud explicit id-t beszúrni
    (a migrate_data.py pont ezt teszi, hogy az ID-k és így az FK-k megmaradjanak).
    Ezért a kombinált sémában `ALWAYS` → `BY DEFAULT` cserét végzünk. Ez normál
    működésnél azonos (id elhagyásakor auto-generál), de explicit id-t is enged.
    Adatimport UTÁN a szekvenciákat `setval`-lal a max(id)-re kell állítani —
    ezt a script külön „after import" blokkba is kiírja.

Futtatás:
    python -m scripts.create_schema
        → írja: scripts/_schema_for_new_project.sql        (1. lépés az Editorban)
                scripts/_sequences_after_import.sql         (3. lépés, import UTÁN)
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

_ROOT = Path(__file__).resolve().parent.parent
_MIG_DIR = _ROOT / "supabase" / "migrations"

# A migrationök kötelező sorrendben (0005 NEM létezik). 0004 = campaign_insights.
_MIGRATIONS = [
    "0001_initial_schema.sql",
    "0002_default_alert_rules.sql",
    "0003_v2_schema_updates.sql",
    "0004_campaign_insights.sql",
    "0006_user_alerts_channel.sql",
    "0007_alerts_email_sent_at.sql",
    "0008_management.sql",
    "0009_client_cascade.sql",
    "0010_account_level.sql",
]

# Identity id-vel rendelkező táblák — ezekre kell adatimport után setval.
_IDENTITY_TABLES = [
    "users", "clients", "ad_accounts", "campaigns", "campaign_insights",
    "campaign_kpis", "ad_account_kpis", "client_kpis",
    "assignments", "account_assignments", "alert_rules",
    "alerts", "mutes", "audit_log",
]

_SCHEMA_OUT = _ROOT / "scripts" / "_schema_for_new_project.sql"
_SEQ_OUT = _ROOT / "scripts" / "_sequences_after_import.sql"
_ALTER_OUT = _ROOT / "scripts" / "_alter_identity_by_default.sql"


def build_schema_sql() -> tuple[str, list[str]]:
    """Visszaadja a kombinált sémát (ALWAYS→BY DEFAULT cserével) + a hiányzó fájlokat."""
    parts: list[str] = [
        "-- ============================================================",
        "-- PPC Monitor — kombinált séma az ÚJ Supabase projekthez",
        "-- Másold be a Supabase SQL Editorba (NEW projekt) és futtasd.",
        "-- (Generálta: scripts/create_schema.py — id-megőrzéshez",
        "--  a 'generated always as identity' → 'generated by default'.)",
        "-- ============================================================",
        "",
    ]
    missing: list[str] = []
    for name in _MIGRATIONS:
        path = _MIG_DIR / name
        if not path.exists():
            missing.append(name)
            continue
        parts.append(f"-- ===== {name} =====")
        parts.append(path.read_text(encoding="utf-8"))
        parts.append("")

    sql = "\n".join(parts)
    # Id-megőrzés: GENERATED ALWAYS AS IDENTITY → GENERATED BY DEFAULT AS IDENTITY.
    sql = re.sub(
        r"generated\s+always\s+as\s+identity",
        "generated by default as identity",
        sql,
        flags=re.IGNORECASE,
    )
    return sql, missing


def build_sequences_sql() -> str:
    """Adatimport UTÁN futtatandó: minden identity-szekvenciát a max(id)-re állít."""
    lines = [
        "-- ============================================================",
        "-- FUTTASD AZ ADATIMPORT (scripts/migrate_data.py) UTÁN!",
        "-- A szekvenciákat a meglévő max(id)-re állítja, hogy a bot",
        "-- következő INSERT-jei ne ütközzenek a migrált ID-kkal.",
        "-- ============================================================",
        "",
    ]
    for table in _IDENTITY_TABLES:
        lines.append(
            f"SELECT setval(pg_get_serial_sequence('public.{table}', 'id'), "
            f"GREATEST((SELECT COALESCE(MAX(id), 0) FROM public.{table}), 1));"
        )
    return "\n".join(lines) + "\n"


def build_alter_identity_sql() -> str:
    """Ha az új séma MÁR létezik 'generated always'-szal: ezzel BY DEFAULT-ra
    váltható DROP nélkül (a meglévő üres táblákon), hogy az id-import működjön."""
    lines = [
        "-- ============================================================",
        "-- HASZNÁLD, HA AZ ÚJ SÉMA MÁR LÉTEZIK 'generated always'-szal.",
        "-- DROP nélkül BY DEFAULT-ra váltja az id oszlopokat, így a",
        "-- migrate_data.py meg tudja őrizni az eredeti ID-kat.",
        "-- (Üres táblákon fuss; adat nem vész el.)",
        "-- ============================================================",
        "",
    ]
    for table in _IDENTITY_TABLES:
        lines.append(f"ALTER TABLE public.{table} ALTER COLUMN id SET GENERATED BY DEFAULT;")
    return "\n".join(lines) + "\n"


def main() -> int:
    if not _MIG_DIR.exists():
        print(f"❌ Nincs migrations könyvtár: {_MIG_DIR}")
        return 1

    schema_sql, missing = build_schema_sql()
    seq_sql = build_sequences_sql()
    alter_sql = build_alter_identity_sql()

    _SCHEMA_OUT.write_text(schema_sql, encoding="utf-8")
    _SEQ_OUT.write_text(seq_sql, encoding="utf-8")
    _ALTER_OUT.write_text(alter_sql, encoding="utf-8")

    print("=" * 60)
    print("  PPC Monitor — séma-generálás az ÚJ projekthez")
    print("=" * 60)
    print(f"✅ Kombinált séma:    {_SCHEMA_OUT}  ({len(schema_sql):,} byte)")
    print(f"✅ Szekvencia-reset:  {_SEQ_OUT}")
    print(f"✅ Identity-fix:      {_ALTER_OUT}  (ha a séma már 'always'-szal létezik)")
    if missing:
        print(f"⚠️ Hiányzó migration fájl(ok): {', '.join(missing)}")
    print("-" * 60)
    print("TEENDŐK:")
    print("  1) Nyisd meg a NEW Supabase projekt → SQL Editor.")
    print(f"  2a) ÚJ séma: másold be a(z) {_SCHEMA_OUT.name}-t, futtasd.")
    print(f"  2b) HA a séma MÁR létezik (generated always): futtasd a(z) {_ALTER_OUT.name}-t.")
    print("  3) Futtasd: python -m scripts.migrate_data   (adatok másolása)")
    print(f"  4) Másold be a(z) {_SEQ_OUT.name} tartalmát az SQL Editorba, futtasd.")
    print("=" * 60)
    print("Megjegyzés: a séma idempotens (IF NOT EXISTS), újrafuttatható.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
