"""
Adatmigráció: régi (PlanSmart) → új (MyMins) Supabase projekt.

ELŐFELTÉTEL: az ÚJ projekt sémája MÁR létezik (lásd scripts/create_schema.py →
SQL Editor). Ez a script CSAK adatot másol, sémát nem hoz létre.

Kapcsolat (mindkettő a .env / .env.new-ból, futásidőben):
    RÉGI:  SUPABASE_URL            + SUPABASE_SERVICE_KEY (vagy SUPABASE_KEY)
    ÚJ:    SUPABASE_URL_NEW        + SUPABASE_KEY_NEW (vagy SUPABASE_SERVICE_KEY_NEW)

Működés:
    - FK-függőségi sorrendben másol (lásd _TABLES).
    - Lapozva olvas a régiből (1000/oldal), és kötegelt upsert-tel ír az újba
      (100/batch), on_conflict='id' → az EREDETI ID-k megmaradnak (ezért kell a
      sémában 'generated by default as identity'; lásd create_schema.py).
    - Hiba esetén NINCS rollback: logol és folytatja a többivel.
    - A végén verify: COUNT(*) régi vs új táblánként.

FONTOS: az `alert_rules` táblát NEM másoljuk — azt a 0002 migration seedeli az
új sémában. Adatimport UTÁN futtasd a scripts/_sequences_after_import.sql-t!

Futtatás:
    python -m scripts.migrate_data --dry-run      # csak kapcsolat + darabszámok
    python -m scripts.migrate_data                # éles másolás (megerősítést kér)
    python -m scripts.migrate_data --yes          # éles, megerősítés nélkül
    python -m scripts.migrate_data --tables clients,users   # részhalmaz
"""
from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import httpx
from dotenv import load_dotenv
from supabase import create_client

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

_ROOT = Path(__file__).resolve().parent.parent
_PAGE = 1000   # olvasási lapméret (régi DB)
_BATCH = 100   # írási kötegméret (új DB)

# FK-függőségi sorrend. (alert_rules KIMARAD — a 0002 seedeli az új sémában.)
_TABLES = [
    "clients",
    "users",
    "ad_accounts",
    "campaigns",
    "campaign_insights",
    "assignments",
    "account_assignments",
    "campaign_kpis",
    "ad_account_kpis",
    "client_kpis",
    "alerts",
    "mutes",
    "audit_log",
]


def _env(*names: str) -> str | None:
    for n in names:
        v = os.getenv(n)
        if v and v.strip():
            return v.strip()
    return None


def _chunks(seq: list, size: int):
    for i in range(0, len(seq), size):
        yield seq[i:i + size]


def _load_credentials() -> tuple[str, str, str, str]:
    load_dotenv(_ROOT / ".env")
    load_dotenv(_ROOT / ".env.new")
    old_url = _env("SUPABASE_URL")
    old_key = _env("SUPABASE_SERVICE_KEY", "SUPABASE_KEY")
    new_url = _env("SUPABASE_URL_NEW", "SUPABASE_NEW_URL", "NEW_SUPABASE_URL")
    new_key = _env("SUPABASE_KEY_NEW", "SUPABASE_SERVICE_KEY_NEW", "SUPABASE_NEW_KEY")

    missing = []
    if not old_url:
        missing.append("SUPABASE_URL (.env)")
    if not old_key:
        missing.append("SUPABASE_SERVICE_KEY/SUPABASE_KEY (.env)")
    if not new_url:
        missing.append("SUPABASE_URL_NEW (.env.new)")
    if not new_key:
        missing.append("SUPABASE_KEY_NEW (.env.new)")
    if missing:
        raise RuntimeError("Hiányzó kapcsolati adat: " + ", ".join(missing))
    return old_url, old_key, new_url, new_key


def _check_conn(url: str, key: str) -> tuple[bool, str]:
    try:
        r = httpx.get(
            url.rstrip("/") + "/rest/v1/",
            headers={"apikey": key, "Authorization": f"Bearer {key}"},
            timeout=20,
        )
        return r.status_code == 200, f"HTTP {r.status_code}"
    except Exception as exc:  # noqa: BLE001
        return False, str(exc)


def preflight_id_insert(new) -> tuple[bool, str]:
    """Ellenőrzi, hogy az ÚJ DB enged-e EXPLICIT id beszúrást (id-megőrzés).

    A séma `generated ALWAYS as identity` esetén a PostgREST NEM tud explicit
    id-t beszúrni → a teljes migráció elhasalna. Ezt egy eldobható próbasorral
    teszteljük (magas id, utána törlés). `generated BY DEFAULT` esetén sikerül.
    """
    probe_id = 999_000_111
    try:
        new.table("clients").upsert(
            {"id": probe_id, "name": "__migration_id_probe__"}, on_conflict="id"
        ).execute()
    except Exception as exc:  # noqa: BLE001
        return False, str(exc)[:200]
    finally:
        try:
            new.table("clients").delete().eq("id", probe_id).execute()
        except Exception:  # noqa: BLE001
            pass
    return True, "explicit id beszúrás OK (generated by default)"


def _count(client, table: str) -> int | None:
    try:
        res = client.table(table).select("id", count="exact").limit(1).execute()
        return res.count
    except Exception:  # noqa: BLE001 — tábla hiányzik / nem elérhető
        return None


def migrate_table(old, new, table: str, *, dry_run: bool) -> dict:
    total = _count(old, table)
    if total is None:
        print(f"  ⚠️ {table}: a régi DB-ben nem elérhető — kihagyva")
        return {"table": table, "old": None, "moved": 0, "errors": 0}

    if dry_run:
        print(f"  {table}: {total} sor (dry-run, nincs írás)")
        return {"table": table, "old": total, "moved": 0, "errors": 0}

    moved = 0
    errors = 0
    start = 0
    while True:
        try:
            rows = (
                old.table(table).select("*").order("id")
                .range(start, start + _PAGE - 1).execute().data
                or []
            )
        except Exception as exc:  # noqa: BLE001
            print(f"\n  ❌ {table}: olvasási hiba @offset {start}: {exc}")
            errors += 1
            break
        if not rows:
            break

        for chunk in _chunks(rows, _BATCH):
            try:
                new.table(table).upsert(chunk, on_conflict="id").execute()
                moved += len(chunk)
            except Exception as exc:  # noqa: BLE001 — log + folytatás (nincs rollback)
                errors += 1
                print(f"\n  ❌ {table}: batch hiba ({len(chunk)} sor): {str(exc)[:160]}")

        start += len(rows)
        print(f"  {table}: {min(start, total)}/{total} másolva", end="\r")
        if len(rows) < _PAGE:
            break

    print(f"  {table}: {moved}/{total} másolva, {errors} hiba" + " " * 10)
    return {"table": table, "old": total, "moved": moved, "errors": errors}


def verify(old, new, tables: list[str]) -> bool:
    print("\nVERIFY — darabszámok (régi vs új):")
    all_ok = True
    for t in tables:
        o = _count(old, t)
        n = _count(new, t)
        ok = (o == n)
        all_ok = all_ok and ok
        mark = "✅" if ok else "❌"
        print(f"  {mark} {t:<20} régi={o}  új={n}")
    return all_ok


def main() -> int:
    parser = argparse.ArgumentParser(description="Supabase adatmigráció (régi → új).")
    parser.add_argument("--dry-run", action="store_true", help="Csak kapcsolat + darabszám, nincs írás")
    parser.add_argument("--yes", action="store_true", help="Megerősítés nélkül futtat (éles írás)")
    parser.add_argument("--tables", help="Vesszős táblalista (alapból mind, FK-sorrendben)")
    args = parser.parse_args()

    print("=" * 60)
    print("  PPC Monitor — Supabase adatmigráció (régi → új)")
    print("=" * 60)

    try:
        old_url, old_key, new_url, new_key = _load_credentials()
    except RuntimeError as exc:
        print(f"❌ {exc}")
        return 1

    old_ok, old_msg = _check_conn(old_url, old_key)
    new_ok, new_msg = _check_conn(new_url, new_key)
    print(f"  RÉGI ({old_url}): {'✅' if old_ok else '❌'} {old_msg}")
    print(f"  ÚJ   ({new_url}): {'✅' if new_ok else '❌'} {new_msg}")
    if not old_ok or not new_ok:
        print("❌ Legalább az egyik kapcsolat nem él — megszakítva.")
        return 1

    old = create_client(old_url, old_key)
    new = create_client(new_url, new_key)

    tables = _TABLES
    if args.tables:
        wanted = [t.strip() for t in args.tables.split(",") if t.strip()]
        tables = [t for t in _TABLES if t in wanted]
        if not tables:
            print(f"❌ Ismeretlen tábla(k): {args.tables} (érvényes: {', '.join(_TABLES)})")
            return 1

    # Dry-run: a régi darabszámok + ellenőrzés, hogy az új séma létezik-e.
    if args.dry_run:
        print("\n[DRY-RUN] forrás darabszámok + cél séma jelenléte:")
        missing_target = []
        for t in tables:
            migrate_table(old, new, t, dry_run=True)
            if _count(new, t) is None:
                missing_target.append(t)
        if missing_target:
            print(
                "\n⚠️ Az ÚJ DB-ben hiányzó/elérhetetlen tábla(k): "
                + ", ".join(missing_target)
                + "\n   → Előbb futtasd a sémát (scripts/create_schema.py → SQL Editor)."
            )
        else:
            print("\n✅ Az ÚJ séma minden céltáblája elérhető.")

        id_ok, id_msg = preflight_id_insert(new)
        if id_ok:
            print(f"✅ ID-megőrzés: {id_msg} — futtatható az éles migráció.")
        else:
            print(
                f"❌ ID-megőrzés NEM működik: {id_msg}\n"
                "   Az új séma 'generated ALWAYS as identity' — a PostgREST így nem enged\n"
                "   explicit id-t. GYORS FIX (DROP nélkül, üres táblákon): futtasd az SQL\n"
                "   Editorban a scripts/_alter_identity_by_default.sql-t, majd újra a dry-runt.\n"
                "   (Generáld: python -m scripts.create_schema)"
            )
        return 0

    # Pre-flight: az id-megőrzés MŰKÖDIK-e? (Nélküle a migráció elhasalna.)
    id_ok, id_msg = preflight_id_insert(new)
    if not id_ok:
        print(
            f"\n❌ ID-megőrzés NEM működik: {id_msg}\n"
            "   Az új séma 'generated ALWAYS as identity'. GYORS FIX (DROP nélkül):\n"
            "   futtasd az SQL Editorban a scripts/_alter_identity_by_default.sql-t\n"
            "   (python -m scripts.create_schema generálja), majd futtasd újra.\n"
            "   Megszakítva — nem írok félkész adatot."
        )
        return 1
    print(f"✅ Pre-flight: {id_msg}")

    # Éles futás — megerősítés (kivéve --yes).
    if not args.yes:
        ans = input(f"\nEz ÍR az ÚJ adatbázisba ({new_url}). Folytatod? (igen/nem): ").strip().lower()
        if ans not in ("igen", "yes", "y", "i"):
            print("Megszakítva.")
            return 1

    print("\nMásolás (FK-sorrendben):")
    results = [migrate_table(old, new, t, dry_run=False) for t in tables]

    ok = verify(old, new, tables)
    total_errors = sum(r["errors"] for r in results)
    print("\n" + "=" * 60)
    if ok and total_errors == 0:
        print("✅ Migráció kész — minden darabszám egyezik.")
        print("   NE FELEJTSD: futtasd a scripts/_sequences_after_import.sql-t az SQL Editorban!")
    else:
        print(f"⚠️ Migráció kész, de van eltérés vagy hiba ({total_errors} batch-hiba) — nézd át a fenti logot.")
    print("=" * 60)
    return 0 if (ok and total_errors == 0) else 1


if __name__ == "__main__":
    sys.exit(main())
